apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.namespace}}
spec:
  replicas: {{.Values.replicas}}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: {{.Values.image}}
        name: guestbook-ui
        ports:
        - containerPort: 80